
vouchers:
  give-100-money:
    description: "Give 100 money"
    command: "eco give %player% 100"
    item:
      display-name: "&a&l$100 Money"
      lore:
        - "&aGive 100 money"
        - "&7Click to give 100 money"
  give-cool-item:
    description: "Give a really cool item"
    command: "give %player% stone 1"
    item:
      display-name: "&d&lCool Item"
      lore:
        - "&7This gives a really cool item"